
const S=JSON.parse(document.getElementById('STATE').textContent);let current=S.cards[0]?.id, pinA=null,pinB=null;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function esc(s){return String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
function showTab(id){$$('.pane').forEach(x=>x.classList.remove('active'));$$('.tabs button').forEach(x=>x.classList.remove('active'));$('#'+id).classList.add('active');$(`[data-tab="${id}"]`)?.classList.add('active');if(id==='field') drawGraph();}
$$('.tabs button').forEach(b=>b.onclick=()=>showTab(b.dataset.tab));
function card(id){return S.cards.find(x=>x.id===id)}
function renderList(q=''){const v=q.toLowerCase();$('#cardlist').innerHTML=S.cards.filter(c=>(c.id+' '+c.title+' '+c.payload).toLowerCase().includes(v)).map(c=>`<div class="item ${c.id===current?'on':''}" data-id="${esc(c.id)}"><b>${String(c.order).padStart(3,'0')} · ${esc(c.title)}</b><div class="small">${esc(c.id)} · ${esc(c.origin)}</div></div>`).join('');$$('#cardlist .item').forEach(x=>x.onclick=()=>selectCard(x.dataset.id));}
function selectCard(id){current=id;let c=card(id);if(!c)return;renderList($('#q').value);let lo=(S.links[id]||[]), bi=(S.backlinks[id]||[]), pa=(S.parents[id]||[]), ch=(S.children[id]||[]);$('#reading').innerHTML=`<h1>${esc(c.title)}</h1><div class="small">${esc(c.id)} · SHA-256 ${esc(c.sha256)}</div><div class="meta"><button onclick="copyPayload()">COPY PAYLOAD</button><button onclick="downloadFile('${esc(c.filename)}')">DOWNLOAD TXT</button><button onclick="pin('A')">PIN A</button><button onclick="pin('B')">PIN B</button><button onclick="surprise()">SURPRISE</button></div><div class="cols"><div class="box"><b>LINKS</b><p>${lo.map(x=>`<a href="#" onclick="jump('${esc(x)}');return false">[[${esc(x)}]]</a>`).join(' · ')||'NONE'}</p><b>BACKLINKS</b><p>${bi.map(x=>`<a href="#" onclick="jump('${esc(x)}');return false">${esc(x)}</a>`).join(' · ')||'NONE'}</p></div><div class="box"><b>LINEAGE</b><p>Parents: ${pa.map(esc).join(', ')||'NONE'}<br>Children: ${ch.map(esc).join(', ')||'NONE'}</p><b>PROVENANCE</b><p>${esc(c.origin)}</p></div></div><div class="payload"><pre>${esc(c.payload)}</pre></div>`;}
function jump(id){if(card(id)){showTab('zettels');selectCard(id)}else{showTab('ghosts');$('#ghostFilter').value=id;renderGhosts(id)}}
function copyPayload(){navigator.clipboard?.writeText(card(current).payload)}
function surprise(){selectCard(S.cards[Math.floor(Math.random()*S.cards.length)].id)}
function pin(which){if(which==='A')pinA=current;else pinB=current;renderCompare()}
function renderCompare(){let a=card(pinA),b=card(pinB);$('#compare').innerHTML=`<div><b>A ${a?esc(a.id):'—'}</b><pre>${a?esc(a.payload):'Pin A from a card.'}</pre></div><div><b>B ${b?esc(b.id):'—'}</b><pre>${b?esc(b.payload):'Pin B from a card.'}</pre></div>`}
$('#q').oninput=e=>renderList(e.target.value);
function renderSources(){ $('#sourcesList').innerHTML=S.sources.map(s=>`<div class="source"><h3>${esc(s.name)}</h3><div>${esc(s.author)} · ${esc(s.year)} · ${esc(s.state)}</div><div class="small">${s.url?`<a href="${esc(s.url)}" target="_blank">${esc(s.url)}</a>`:'PRIVATE LOCAL SOURCE'}</div><div class="small">Used by: ${esc((s.used_by||[]).join(', ')||'none')}</div></div>`).join('')}
function renderGhosts(q=''){q=q.toLowerCase();let arr=Object.entries(S.ghosts).filter(([g])=>g.toLowerCase().includes(q));$('#ghostList').innerHTML=arr.map(([g,refs])=>`<div class="ghost"><b>${esc(g)}</b><div>${refs.length} inbound occurrences<br><span class="small">${esc([...new Set(refs.map(r=>r.source))].join(', '))}</span></div></div>`).join('')||'<p>No match.</p>'}
$('#ghostFilter').oninput=e=>renderGhosts(e.target.value);
function downloadFile(name){let content=S.embeddedFiles[name];if(content===undefined){alert('Not embedded in standalone index: '+name);return}let b=new Blob([content],{type:'text/plain;charset=utf-8'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=name.split('/').pop();a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
function renderDownloads(){let names=Object.keys(S.embeddedFiles).sort();$('#files').innerHTML=names.map(n=>`<button class="download" onclick="downloadFile('${esc(n).replaceAll("'","\\'")}')">${esc(n)}</button>`).join('')}
function drawGraph(){let svg=$('#graph'); if(svg.dataset.done)return;svg.dataset.done=1;let Z=S.nodes.filter(n=>n.type==='ZETTEL'), G=S.nodes.filter(n=>n.type==='GHOST'), P=S.nodes.filter(n=>n.type==='PLATFORM'), So=S.nodes.filter(n=>n.type==='SOURCE'), R=S.nodes.filter(n=>n.type==='RESOURCE'), Pr=S.nodes.filter(n=>n.type==='PROMPT');let all=[...Z,...G,...P,...So,...R,...Pr];let W=1200,H=850,pos={};Z.forEach((n,i)=>{let col=n.id.startsWith('MARTINA')?0:n.id.startsWith('THEORY')?1:2;let arr=Z.filter(x=>(x.id.startsWith('MARTINA')?0:x.id.startsWith('THEORY')?1:2)===col);let j=arr.findIndex(x=>x.id===n.id);pos[n.id]={x:140+col*360,y:35+j*(650/Math.max(1,arr.length-1))}});G.forEach((n,i)=>pos[n.id]={x:1110,y:55+i*58});P.forEach((n,i)=>pos[n.id]={x:850+(i%3)*95,y:55+Math.floor(i/3)*48});So.forEach((n,i)=>pos[n.id]={x:930+(i%2)*140,y:440+Math.floor(i/2)*34});R.forEach((n,i)=>pos[n.id]={x:1160+(i%2)*140,y:500+Math.floor(i/2)*30});Pr.forEach((n,i)=>pos[n.id]={x:1040+i*180,y:690});let edges=S.relations.filter(r=>['LINKS_TO','MEMBER_OF'].includes(r.type)&&pos[r.source]&&pos[r.target]);svg.setAttribute('viewBox',`0 0 ${W} ${H}`);svg.innerHTML=edges.map(e=>`<line x1="${pos[e.source].x}" y1="${pos[e.source].y}" x2="${pos[e.target].x}" y2="${pos[e.target].y}" stroke="#ccc" stroke-width=".7"/>`).join('')+all.filter(n=>pos[n.id]).map(n=>{let p=pos[n.id],r=n.type==='ZETTEL'?5:3.5;return `<g><circle cx="${p.x}" cy="${p.y}" r="${r}" fill="${n.type==='ZETTEL'?'#111':n.type==='GHOST'?'#fff':'#888'}" stroke="#111"/><title>${esc(n.id)} · ${esc(n.title)}</title></g>`}).join('')}
$('#paperText').textContent=S.paper.replace(/^\\.*$/gm,'');$('#sourceMapText').textContent=S.sourceMap;$('#promptText').textContent=S.assemblyPrompt;$('#reproduceText').textContent=S.start+'\n\n'+S.makingHistory+'\n\nASSEMBLY PROMPT SHA-256: '+S.promptHash;renderList();selectCard(current);renderCompare();renderSources();renderGhosts();renderDownloads();showTab('start');
